"""empty message

Revision ID: 0ee0d7d63b3a
Revises: e55766f0222e
Create Date: 2019-12-11 16:53:23.159126

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '0ee0d7d63b3a'
down_revision = 'e55766f0222e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('comment_num', sa.Integer(), nullable=True))
    op.drop_constraint('post_ibfk_3', 'post', type_='foreignkey')
    op.create_foreign_key(None, 'post', 'comment', ['comment_num'], ['id'])
    op.drop_column('post', 'comment_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('comment_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'post', type_='foreignkey')
    op.create_foreign_key('post_ibfk_3', 'post', 'comment', ['comment_id'], ['id'])
    op.drop_column('post', 'comment_num')
    # ### end Alembic commands ###
