"""empty message

Revision ID: 80160300c846
Revises: fedd1d8cc256
Create Date: 2019-12-12 10:29:45.507527

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '80160300c846'
down_revision = 'fedd1d8cc256'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('api_test_case',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('case_name', sa.String(length=50), nullable=False),
    sa.Column('request_url', sa.String(length=200), nullable=False),
    sa.Column('request_data', sa.String(length=200), nullable=False),
    sa.Column('request_method', sa.String(length=10), nullable=False),
    sa.Column('request_expected_result', sa.String(length=200), nullable=False),
    sa.Column('request_result', sa.String(length=200), nullable=False),
    sa.Column('operator', sa.String(length=200), nullable=False),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('api_test_case')
    # ### end Alembic commands ###
