"""empty message

Revision ID: a9851f087c3e
Revises: bb4d3ada63a2
Create Date: 2019-12-17 15:24:34.576373

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a9851f087c3e'
down_revision = 'bb4d3ada63a2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('api_test_case', sa.Column('request_return_result', sa.String(length=200), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('api_test_case', 'request_return_result')
    # ### end Alembic commands ###
